#!/bin/bash

# basic script to easily serve the html report generated by the test

set -e
trap 'catch $? $LINENO' ERR
catch() {
	echo "Error $1 occurred on $2"
}
set -euo pipefail

SCRIPT_PATH=$0
REAL_SCRIPT_PATH=$(readlink -f ${SCRIPT_PATH})
SCRIPT_DIR=$(dirname ${REAL_SCRIPT_PATH})

SCRIPT_NAME=$(basename "${SCRIPT_PATH}")
REAL_SCRIPT_NAME=$(basename "${REAL_SCRIPT_PATH}")

SCRIPT_VERSION="20210917"

DRV_NAME="rtl8814au"
DRV_VERSION=$(sed -n "s/^#define DRIVERVERSION\\t\"v\\([^\"][^\"]*\\)\"\$/\\1/p" include/rtw_version.h)
DEB_VERSION=$(sed -n "s/^[^(]*(\\([^)]*\\)).*/\\1/p" debian/changelog | head -1)
# TODO: check if the deb_version starts with the drv_version
OPTIONS_FILE="8814au.conf"
TARGET_ARCH=${TARGET_ARCH:-$(uname -m)}

# fix ARCH name to deb package style
case "${TARGET_ARCH}" in
	x86_64)
		TARGET_ARCH=amd64
		;;
	*)
		# Do nothing if unknown
		:;
		;;
esac

DEB_NAME="${DRV_NAME}-dkms_${DEB_VERSION}_${TARGET_ARCH}.deb"

DRV_DIR="$(pwd)"
KRNL_VERSION="$(uname -r)"

NO_PROMPT=0
NO_INSTALL=0
BUILD_DEB=0
INSTALL_DEB=0

show_help () {
	echo "Syntax $0 <NoPrompt>"
	echo "       NoInstall     compile only; do not install the build"
	echo "       NoPrompt      noninteractive mode; no reboot"
	echo "       Deb           build the dkms build package"
	echo "       DebInstall    build the dkms build package"
	echo "       -h|--help - Show help"
}

echo "Running ${SCRIPT_NAME} version ${SCRIPT_VERSION} for driver version ${DRV_VERSION} for ${TARGET_ARCH}"

# TODO: patch the config base on the arch

if [[ $# -gt 0 ]]; then
	CAPTURED_PARAMS=( "$@" )
	# Get the options
	for cur_param in "${CAPTURED_PARAMS[@]}"; do
		case "${cur_param}" in
			NoPrompt)
				NO_PROMPT=1 ;;
			NoInstall)
				NO_INSTALL=1 ;;
			Deb)
				NO_INSTALL=1
				BUILD_DEB=1
				;;
			DebInstall)
				NO_INSTALL=1
				BUILD_DEB=1
				INSTALL_DEB=1
				;;
			-h|-help|--help)
				show_help
				exec true ;;
			*)
				show_help
				exit 1
				;;
		esac
	done
fi

# check for previous installation
if [[ "${NO_INSTALL}" -ne 1 ]]; then
	if [[ -d "/usr/src/${DRV_NAME}-${DRV_VERSION}" ]]; then
		>&2 echo "It appears that this driver may already be installed."
		>&2 echo "You will need to run the following before installing."
		>&2 echo "$ sudo ./remove-driver.sh"
		false
	fi
fi

echo "Starting build..."

# Build / Install as a deb package
if [[ "${BUILD_DEB}" -eq 1 ]]; then
	echo "Output deb: ${DEB_NAME}"
	rm -f "${DEB_NAME}"
	dpkg-buildpackage -b -rfakeroot
	cp "$(pwd)/../${DEB_NAME}" .
	if [[ "${INSTALL_DEB}" -eq 1 ]]; then
		if [[ "${EUID}" -ne 0 ]]; then
			exec sudo -E apt-get ${APT_OPTS:-} install "$(pwd)/../${DEB_NAME}"
		else
			exec apt-get ${APT_OPTS:-} install "$(pwd)/../${DEB_NAME}"
		fi
		exec echo "The driver was installed successfully."
	fi
	exec echo "The driver was built successfully."
fi

// Compile the actual kernel module
make
if [[ "${NO_INSTALL}" -ne 1 ]]; then
	echo "Starting installation..."
	if [[ "${EUID}" -ne 0 ]]; then
		sudo make dkms_install
	else
		make dkms_install
	fi
	echo "The driver was installed successfully."
else
	echo "The driver was built successfully."
fi

if [[ "${NO_INSTALL}" -ne 1 && "${NO_PROMPT}" -ne 1 ]]; then
	read -p "Do you want to edit the driver options file now? [y/N] " -n 1 -r
	printf "\n"
	if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
		if [[ "${EUID}" -ne 0 ]]; then
			sudo nano /etc/modprobe.d/"${OPTIONS_FILE}"
		else
			nano /etc/modprobe.d/"${OPTIONS_FILE}"
		fi
	fi

	read -p "Do you want to reboot now? [y/N] " -n 1 -r
	echo    # move to a new line
	if [[ "${REPLY}" =~ ^[Yy]$ ]]
	then
		if [[ "${EUID}" -ne 0 ]]; then
			sudo reboot
		else
			reboot
		fi
	fi
fi
